<html lang="es">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<style type="text/css">
    body {
        font-family: "Zap";
    }
    
    h1 {
        font-style:italic;
    }
</style>
</head>
<body>
<div>

<?php foreach ($this->klear['menu'] as $menu):?>
<h1><?php echo $this->nogettext($menu['title']);?></h1>
    <?php if (isset($menu['description'])):?>
      <p><?php echo $this->nogettext($menu['description']);?></p>
    <?php endif;?>
    <?php foreach ($menu['submenus'] as $key => $submenu):?>
        <h2 id="<?php echo $key;?>">
        <?php if ($submenu['class']):?>
            <img alt="<?php echo $submenu['class'];?>" src="<?php echo $this->geticon($submenu['class'],$this->path);?>" /> <?php echo $this->nogettext($submenu['title']);?>
        <?php else:?>
            <?php echo $this->nogettext($submenu['title']);?>
        <?php endif;?>
        </h2>
        <?php if (isset($submenu['description'])):?>
        <p><?php echo $this->nogettext($submenu['description']);?></p>
        <?php endif;?>
        <?php if (isset($this->entity[$key]['fields'])):?>
            <h3>Listado</h3>
            
            <!-- Campos de las entidades -->
            <h4>Campos</h4>
            
            <ul>
            <?php 
            foreach ($this->entity[$key]['fields'] as $campoKey => $campo) {
                foreach ($this->list[$key]['screens'] as $list) {
                    if ($list['controller'] == 'list') {
                        $black = false;
                        if (isset($list['fields']['blacklist'])) {
                            foreach ($list['fields']['blacklist'] as $blacklistKey => $blacklistList) {
                                if (($campoKey == $blacklistKey) && $blacklistList) {
                                    $black = true;
                                }
                            }
                        }
                        
                        if (!$black) {
                            if (isset($campo['type'])) {
                                if ($campo['type'] != 'select') {
                                    echo '<li>'.$this->nogettext($campo['title']).' ('.$campo['type'].')</li>';
                                } else {
                                    echo '<li>'.$this->nogettext($campo['title']).' ('.$campo['type'].': ';
                                    if ($campo['source']['data'] == 'inline') {
                                        $valueSelect = array();
                                        foreach ($campo['source']['values'] as $value) {
                                            if (!is_array($value)) {
                                            $valueSelect[] = $this->nogettext($value);
                                            } else {
                                            $valueSelect[] = $this->nogettext($value['title']);
                                            }
                                        }
                                        
                                        echo implode(' / ',$valueSelect);
                                        
                                    } else {
                                        
                                        
                                        $yamlModel = end(explode("\\",$campo['source']['config']['mapperName']));
                                        
                                        $a = array();
                                        $b = array();
                                        
                                        $yamlClass = Generator_Doc_YamlImporter::getYaml('/model/'.$yamlModel);
                                        
                                        foreach ($campo['source']['config']['fieldName']['fields'] as $subCampo) {
                                            if (isset($yamlClass) && isset($yamlClass['fields'][$subCampo])) {
                                                $a[] = '%'.$subCampo.'%';
                                                $b[] = $this->nogettext($yamlClass['fields'][$subCampo]['title']);
                                            }
                                        }
                                        
                                        $bodytag = str_replace($a, $b, $campo['source']['config']['fieldName']['template']);
                                        
                                        echo $bodytag;
                                    }
                                    echo ')</li>';
                                }
                            }
                        }
                        break;
                    }
                }
            }
            ?>
            </ul>
            <?php foreach ($this->list[$key]['screens'] as $list):?>
            
                <?php if ($list['controller'] == 'list'):?>
                    <?php if (isset($list['options']['screens'])):?>
                        <!-- Las pantallas disponibles -->
                        <?php if (isset($list['info'])):?>
                        <ul>
                            <strong><?php echo $this->nogettext($list['info']['label']);?></strong>
                            <p><?php echo $this->nogettext($list['info']['text']);?></p>
                        </ul>
                        <?php endif;?>
                        
                        <!-- Screens -->
                        <h4><?php echo $this->nogettext($list['options']['title']);?></h4>
                        <ul>
                        <?php foreach ($list['options']['screens'] as $keyScreen => $value):?>
                            <li>
                                <img src="<?php echo $this->geticon($this->list[$key]['screens'][$keyScreen]['class'],$this->path);?>" />
                                <?php echo $this->nogettext($this->list[$key]['screens'][$keyScreen]['title']);?>
                                <?php if (isset($this->list[$key]['screens'][$keyScreen]['info'])):?>
                                <ul>
                                    <strong><?php echo $this->nogettext($this->list[$key]['screens'][$keyScreen]['info']['label']);?></strong>
                                    <p><?php echo $this->nogettext($this->list[$key]['screens'][$keyScreen]['info']['text']);?></p>
                                </ul>
                                <?php endif;?>
                            </li>
                        <?php endforeach;?>
                        
                        <!-- Dialogs -->
                        <?php if (isset($list['options']['dialogs'])): ?>
                        <?php foreach ($list['options']['dialogs'] as $keyDialog => $value):?>
                            <li>
                                <img src="<?php echo $this->geticon($this->list[$key]['dialogs'][$keyDialog]['class'],$this->path);?>" />
                                <?php echo $this->nogettext($this->list[$key]['dialogs'][$keyDialog]['title']);?>
                            </li>
                        <?php endforeach;?>
                        <?php endif;?>
                        </ul>
                    <?php endif;?>
                    
                    <?php if (isset($list['fields']['options']['screens'])):?>
                        <!-- Las opciones disponibles -->
                        <h4><?php echo $this->nogettext($list['fields']['options']['title']);?></h4>
                        <ul>
                        <!-- Screens -->
                        <?php foreach ($list['fields']['options']['screens'] as $keyScreen => $value):?>
                        <li>
                            <?php if (isset($this->list[$key]['screens'][$keyScreen]['class'])):?>
                                <img src="<?php echo $this->geticon($this->list[$key]['screens'][$keyScreen]['class'],$this->path);?>" />
                            <?php endif;?>
                            <?php echo $this->nogettext($this->list[$key]['screens'][$keyScreen]['title'],$this->list[$key]);?>
                        </li>
                        <?php endforeach;?>
                        
                        <!-- Dialogs -->
                        <?php if (isset($list['fields']['options']['dialogs'])):?>
                        <?php foreach ($list['fields']['options']['dialogs'] as $keyDialog => $value):?>
                        <li>
                            <img src="<?php echo $this->geticon($this->list[$key]['dialogs'][$keyDialog]['class'],$this->path);?>" />
                            <?php echo $this->nogettext($this->list[$key]['dialogs'][$keyDialog]['title'],$this->list[$key]);?>
                        </li>
                        
                        <?php endforeach;?>
                        <?php endif;?>
                        </ul>
                    <?php endif;?>
                    
                    <?php break;?>
                    
                <?php endif;?>
                
            <?php endforeach;?>
        <?php endif;?>
    <?php endforeach;?>
<?php endforeach;?>
</div>
</body>
</html>